### ISSUE TITLE
Please include Python file

### ISSUE THREAD

**Issue by baileypierson** [barrycahill/intro-data-capstone-biodiversity#1]
Hi there,

My name is Bailey and I work on the Codecademy Project Review team. I was attempting to review your project, but was not able to, because you’re missing the Python file containing your code. 

In order to receive a review, please upload the missing file directly to your project repo using these instructions. 

Once you’ve completed your project and uploaded it to this repo, you will be able to receive a review. To do so, **please notify Customer Support by submitting a request via [this form](https://help.codecademy.com/hc/en-us/requests/new)**. 

Fill out the form using the following template:
```
*Subject*: Request for Project Review

*Description*:

I am submitting a project for review as there was an error with my previous submission. 

Please see information below:

Intensive Name:
Cohort Start Date:
 Project Title:
Git Repo Link:
```

Thanks,
Bailey & the Codecademy Team

**Comment by barrycahill** [comment]
On the submissions site, it says:
"If you completed this project on codecademy.com rather than on your own computer, please create a readme.txt file that says “Completed Code in the Learning Environment”
I included that readme.txt.
As it was done on the site, there is no .py file.
Did I misunderstand the instructions?

**Comment by barrycahill** [comment]
ok, thanks!

**Comment by bengalspice** [comment]
I'll grade your project. There seems to be confusion on what is accepted for IDA capstones. The work you did in the Learning Environment is acceptable.
